// <auto-generated />
using System;
using AirlineMicroservice.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AirlineMicroservice.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200805120419_Migration1")]
    partial class Migration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AirlineMicroservice.Models.Airline", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4")
                        .HasMaxLength(20);

                    b.Property<string>("Address")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Image")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("Rating")
                        .HasColumnType("double");

                    b.HasKey("Name");

                    b.ToTable("Airlines");
                });

            modelBuilder.Entity("AirlineMicroservice.Models.ArilineRating", b =>
                {
                    b.Property<int>("AirlineRatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AirlineName")
                        .IsRequired()
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("AirlineRatingId");

                    b.HasIndex("AirlineName");

                    b.ToTable("ArilineRating");
                });

            modelBuilder.Entity("AirlineMicroservice.Models.Connection", b =>
                {
                    b.Property<int>("ConntectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ConntectionId");

                    b.HasIndex("FlightId");

                    b.ToTable("Connection");
                });

            modelBuilder.Entity("AirlineMicroservice.Models.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AirlineName")
                        .IsRequired()
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4");

                    b.Property<string>("Value")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("DestinationId");

                    b.HasIndex("AirlineName");

                    b.ToTable("Destination");
                });

            modelBuilder.Entity("AirlineMicroservice.Models.FastTicket", b =>
                {
                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.Property<string>("AirlineName")
                        .IsRequired()
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4");

                    b.Property<double>("NewPrice")
                        .HasColumnType("double");

                    b.HasKey("SeatId");

                    b.HasIndex("AirlineName");

                    b.ToTable("FastTickets");
                });

            modelBuilder.Entity("AirlineMicroservice.Models.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AirlineName")
                        .IsRequired()
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4");

                    b.Property<DateTime>("Arrival")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Departure")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Destination")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("Distance")
                        .HasColumnType("double");

                    b.Property<string>("Origin")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("FlightId");

                    b.HasIndex("AirlineName");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("AirlineMicroservice.Models.FlightRating", b =>
                {
                    b.Property<int>("FlightRatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("FlightRatingId");

                    b.HasIndex("FlightId");

                    b.ToTable("FlightRating");
                });

            modelBuilder.Entity("AirlineMicroservice.Models.FlightReservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Creator")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("FinalPrice")
                        .HasColumnType("double");

                    b.Property<DateTime>("TimeOfCreation")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("VehicleReservationId")
                        .HasColumnType("int");

                    b.HasKey("ReservationId");

                    b.ToTable("FlightReservations");
                });

            modelBuilder.Entity("AirlineMicroservice.Models.FlightReservationDetail", b =>
                {
                    b.Property<int>("FlightReservationDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AirlineName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<int>("FlightReservationReservationId")
                        .HasColumnType("int");

                    b.HasKey("FlightReservationDetailId");

                    b.HasIndex("FlightReservationReservationId");

                    b.ToTable("FlightReservationDetail");
                });

            modelBuilder.Entity("AirlineMicroservice.Models.PassengerSeat", b =>
                {
                    b.Property<int>("PassengerSeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Accepted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AirlineScored")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("FlightReservationDetailId")
                        .HasColumnType("int");

                    b.Property<bool>("FlightScored")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Passport")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Username")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("PassengerSeatId");

                    b.HasIndex("FlightReservationDetailId");

                    b.ToTable("PassengerSeat");
                });

            modelBuilder.Entity("AirlineMicroservice.Models.Price", b =>
                {
                    b.Property<int>("PriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AirlineName")
                        .IsRequired()
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("double");

                    b.HasKey("PriceId");

                    b.HasIndex("AirlineName");

                    b.ToTable("Price");
                });

            modelBuilder.Entity("AirlineMicroservice.Models.Seat", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Discount")
                        .HasColumnType("double");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("Occupied")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<string>("Type")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("SeatId");

                    b.HasIndex("FlightId");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("AirlineMicroservice.Models.SeatArrangement", b =>
                {
                    b.Property<int>("SeatArrangementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AirlineName")
                        .IsRequired()
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("double");

                    b.HasKey("SeatArrangementId");

                    b.HasIndex("AirlineName");

                    b.ToTable("SeatArrangement");
                });

            modelBuilder.Entity("AirlineMicroservice.Models.SeatArrangementFlight", b =>
                {
                    b.Property<int>("SeatArrangementFlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("double");

                    b.HasKey("SeatArrangementFlightId");

                    b.HasIndex("FlightId");

                    b.ToTable("SeatArrangementFlight");
                });

            modelBuilder.Entity("AirlineMicroservice.Models.Segment", b =>
                {
                    b.Property<int>("SegmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AirlineName")
                        .IsRequired()
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("double");

                    b.HasKey("SegmentId");

                    b.HasIndex("AirlineName");

                    b.ToTable("Segment");
                });

            modelBuilder.Entity("AirlineMicroservice.Models.SegmentFlight", b =>
                {
                    b.Property<int>("SegmentFlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("double");

                    b.HasKey("SegmentFlightId");

                    b.HasIndex("FlightId");

                    b.ToTable("SegmentFlight");
                });

            modelBuilder.Entity("AirlineMicroservice.Models.ArilineRating", b =>
                {
                    b.HasOne("AirlineMicroservice.Models.Airline", "Airline")
                        .WithMany("Ratings")
                        .HasForeignKey("AirlineName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AirlineMicroservice.Models.Connection", b =>
                {
                    b.HasOne("AirlineMicroservice.Models.Flight", "Flight")
                        .WithMany("Connections")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AirlineMicroservice.Models.Destination", b =>
                {
                    b.HasOne("AirlineMicroservice.Models.Airline", "Airline")
                        .WithMany("Destinations")
                        .HasForeignKey("AirlineName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AirlineMicroservice.Models.FastTicket", b =>
                {
                    b.HasOne("AirlineMicroservice.Models.Airline", "Airline")
                        .WithMany("FastTickets")
                        .HasForeignKey("AirlineName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AirlineMicroservice.Models.Flight", b =>
                {
                    b.HasOne("AirlineMicroservice.Models.Airline", "Airline")
                        .WithMany("Flights")
                        .HasForeignKey("AirlineName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AirlineMicroservice.Models.FlightRating", b =>
                {
                    b.HasOne("AirlineMicroservice.Models.Flight", "Flight")
                        .WithMany("Ratings")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AirlineMicroservice.Models.FlightReservationDetail", b =>
                {
                    b.HasOne("AirlineMicroservice.Models.FlightReservation", "FlightReservation")
                        .WithMany("FlightReservationDetails")
                        .HasForeignKey("FlightReservationReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AirlineMicroservice.Models.PassengerSeat", b =>
                {
                    b.HasOne("AirlineMicroservice.Models.FlightReservationDetail", "FlightReservationDetail")
                        .WithMany("PassengerSeats")
                        .HasForeignKey("FlightReservationDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AirlineMicroservice.Models.Price", b =>
                {
                    b.HasOne("AirlineMicroservice.Models.Airline", "Airline")
                        .WithMany("Prices")
                        .HasForeignKey("AirlineName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AirlineMicroservice.Models.Seat", b =>
                {
                    b.HasOne("AirlineMicroservice.Models.Flight", "Flight")
                        .WithMany("Seats")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AirlineMicroservice.Models.SeatArrangement", b =>
                {
                    b.HasOne("AirlineMicroservice.Models.Airline", "Airline")
                        .WithMany("SeatingArrangements")
                        .HasForeignKey("AirlineName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AirlineMicroservice.Models.SeatArrangementFlight", b =>
                {
                    b.HasOne("AirlineMicroservice.Models.Flight", "Flight")
                        .WithMany("SeatingArrangements")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AirlineMicroservice.Models.Segment", b =>
                {
                    b.HasOne("AirlineMicroservice.Models.Airline", "Airline")
                        .WithMany("SegmentLengths")
                        .HasForeignKey("AirlineName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AirlineMicroservice.Models.SegmentFlight", b =>
                {
                    b.HasOne("AirlineMicroservice.Models.Flight", "Flight")
                        .WithMany("SegmentLengths")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
